// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol_defn.proto

package com.example.tutorial;

public final class ResultProto {
  private ResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CourseMarksOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.CourseMarks)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 score = 2;</code>
     */
    boolean hasScore();
    /**
     * <code>optional int32 score = 2;</code>
     */
    int getScore();
  }
  /**
   * Protobuf type {@code tutorial.CourseMarks}
   */
  public  static final class CourseMarks extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.CourseMarks)
      CourseMarksOrBuilder {
    // Use CourseMarks.newBuilder() to construct.
    private CourseMarks(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CourseMarks() {
      name_ = "";
      score_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CourseMarks(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              score_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.ResultProto.internal_static_tutorial_CourseMarks_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.ResultProto.internal_static_tutorial_CourseMarks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tutorial.ResultProto.CourseMarks.class, com.example.tutorial.ResultProto.CourseMarks.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private int score_;
    /**
     * <code>optional int32 score = 2;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 score = 2;</code>
     */
    public int getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, score_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, score_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.tutorial.ResultProto.CourseMarks)) {
        return super.equals(obj);
      }
      com.example.tutorial.ResultProto.CourseMarks other = (com.example.tutorial.ResultProto.CourseMarks) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasScore() == other.hasScore());
      if (hasScore()) {
        result = result && (getScore()
            == other.getScore());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasScore()) {
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + getScore();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.tutorial.ResultProto.CourseMarks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.ResultProto.CourseMarks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.CourseMarks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.ResultProto.CourseMarks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.CourseMarks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.tutorial.ResultProto.CourseMarks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.CourseMarks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.tutorial.ResultProto.CourseMarks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.CourseMarks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.tutorial.ResultProto.CourseMarks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.tutorial.ResultProto.CourseMarks prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.CourseMarks}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.CourseMarks)
        com.example.tutorial.ResultProto.CourseMarksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.ResultProto.internal_static_tutorial_CourseMarks_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.ResultProto.internal_static_tutorial_CourseMarks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.tutorial.ResultProto.CourseMarks.class, com.example.tutorial.ResultProto.CourseMarks.Builder.class);
      }

      // Construct using com.example.tutorial.ResultProto.CourseMarks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.ResultProto.internal_static_tutorial_CourseMarks_descriptor;
      }

      public com.example.tutorial.ResultProto.CourseMarks getDefaultInstanceForType() {
        return com.example.tutorial.ResultProto.CourseMarks.getDefaultInstance();
      }

      public com.example.tutorial.ResultProto.CourseMarks build() {
        com.example.tutorial.ResultProto.CourseMarks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.tutorial.ResultProto.CourseMarks buildPartial() {
        com.example.tutorial.ResultProto.CourseMarks result = new com.example.tutorial.ResultProto.CourseMarks(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.ResultProto.CourseMarks) {
          return mergeFrom((com.example.tutorial.ResultProto.CourseMarks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.tutorial.ResultProto.CourseMarks other) {
        if (other == com.example.tutorial.ResultProto.CourseMarks.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.tutorial.ResultProto.CourseMarks parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.tutorial.ResultProto.CourseMarks) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int score_ ;
      /**
       * <code>optional int32 score = 2;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 score = 2;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>optional int32 score = 2;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 score = 2;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.CourseMarks)
    }

    // @@protoc_insertion_point(class_scope:tutorial.CourseMarks)
    private static final com.example.tutorial.ResultProto.CourseMarks DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.tutorial.ResultProto.CourseMarks();
    }

    public static com.example.tutorial.ResultProto.CourseMarks getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CourseMarks>
        PARSER = new com.google.protobuf.AbstractParser<CourseMarks>() {
      public CourseMarks parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CourseMarks(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CourseMarks> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CourseMarks> getParserForType() {
      return PARSER;
    }

    public com.example.tutorial.ResultProto.CourseMarks getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string lastname = 2;</code>
     */
    boolean hasLastname();
    /**
     * <code>required string lastname = 2;</code>
     */
    java.lang.String getLastname();
    /**
     * <code>required string lastname = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    /**
     * <code>required string firstname = 3;</code>
     */
    boolean hasFirstname();
    /**
     * <code>required string firstname = 3;</code>
     */
    java.lang.String getFirstname();
    /**
     * <code>required string firstname = 3;</code>
     */
    com.google.protobuf.ByteString
        getFirstnameBytes();

    /**
     * <code>optional string email = 4;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    java.util.List<com.example.tutorial.ResultProto.CourseMarks> 
        getMarksList();
    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    com.example.tutorial.ResultProto.CourseMarks getMarks(int index);
    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    int getMarksCount();
    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    java.util.List<? extends com.example.tutorial.ResultProto.CourseMarksOrBuilder> 
        getMarksOrBuilderList();
    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    com.example.tutorial.ResultProto.CourseMarksOrBuilder getMarksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Student)
      StudentOrBuilder {
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      id_ = "";
      lastname_ = "";
      firstname_ = "";
      email_ = "";
      marks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              lastname_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              firstname_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              email_ = bs;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                marks_ = new java.util.ArrayList<com.example.tutorial.ResultProto.CourseMarks>();
                mutable_bitField0_ |= 0x00000010;
              }
              marks_.add(
                  input.readMessage(com.example.tutorial.ResultProto.CourseMarks.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          marks_ = java.util.Collections.unmodifiableList(marks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.ResultProto.internal_static_tutorial_Student_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.ResultProto.internal_static_tutorial_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tutorial.ResultProto.Student.class, com.example.tutorial.ResultProto.Student.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastname_;
    /**
     * <code>required string lastname = 2;</code>
     */
    public boolean hasLastname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string lastname = 2;</code>
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string lastname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object firstname_;
    /**
     * <code>required string firstname = 3;</code>
     */
    public boolean hasFirstname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string firstname = 3;</code>
     */
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string firstname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 4;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MARKS_FIELD_NUMBER = 5;
    private java.util.List<com.example.tutorial.ResultProto.CourseMarks> marks_;
    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    public java.util.List<com.example.tutorial.ResultProto.CourseMarks> getMarksList() {
      return marks_;
    }
    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    public java.util.List<? extends com.example.tutorial.ResultProto.CourseMarksOrBuilder> 
        getMarksOrBuilderList() {
      return marks_;
    }
    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    public int getMarksCount() {
      return marks_.size();
    }
    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    public com.example.tutorial.ResultProto.CourseMarks getMarks(int index) {
      return marks_.get(index);
    }
    /**
     * <code>repeated .tutorial.CourseMarks marks = 5;</code>
     */
    public com.example.tutorial.ResultProto.CourseMarksOrBuilder getMarksOrBuilder(
        int index) {
      return marks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFirstname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, firstname_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      for (int i = 0; i < marks_.size(); i++) {
        output.writeMessage(5, marks_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, firstname_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      for (int i = 0; i < marks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, marks_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.tutorial.ResultProto.Student)) {
        return super.equals(obj);
      }
      com.example.tutorial.ResultProto.Student other = (com.example.tutorial.ResultProto.Student) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasLastname() == other.hasLastname());
      if (hasLastname()) {
        result = result && getLastname()
            .equals(other.getLastname());
      }
      result = result && (hasFirstname() == other.hasFirstname());
      if (hasFirstname()) {
        result = result && getFirstname()
            .equals(other.getFirstname());
      }
      result = result && (hasEmail() == other.hasEmail());
      if (hasEmail()) {
        result = result && getEmail()
            .equals(other.getEmail());
      }
      result = result && getMarksList()
          .equals(other.getMarksList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasLastname()) {
        hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastname().hashCode();
      }
      if (hasFirstname()) {
        hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstname().hashCode();
      }
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      if (getMarksCount() > 0) {
        hash = (37 * hash) + MARKS_FIELD_NUMBER;
        hash = (53 * hash) + getMarksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.tutorial.ResultProto.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.ResultProto.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.ResultProto.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.tutorial.ResultProto.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.tutorial.ResultProto.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.tutorial.ResultProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.tutorial.ResultProto.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Student)
        com.example.tutorial.ResultProto.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.ResultProto.internal_static_tutorial_Student_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.ResultProto.internal_static_tutorial_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.tutorial.ResultProto.Student.class, com.example.tutorial.ResultProto.Student.Builder.class);
      }

      // Construct using com.example.tutorial.ResultProto.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMarksFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        firstname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (marksBuilder_ == null) {
          marks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          marksBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.ResultProto.internal_static_tutorial_Student_descriptor;
      }

      public com.example.tutorial.ResultProto.Student getDefaultInstanceForType() {
        return com.example.tutorial.ResultProto.Student.getDefaultInstance();
      }

      public com.example.tutorial.ResultProto.Student build() {
        com.example.tutorial.ResultProto.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.tutorial.ResultProto.Student buildPartial() {
        com.example.tutorial.ResultProto.Student result = new com.example.tutorial.ResultProto.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastname_ = lastname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.firstname_ = firstname_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.email_ = email_;
        if (marksBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            marks_ = java.util.Collections.unmodifiableList(marks_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.marks_ = marks_;
        } else {
          result.marks_ = marksBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.ResultProto.Student) {
          return mergeFrom((com.example.tutorial.ResultProto.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.tutorial.ResultProto.Student other) {
        if (other == com.example.tutorial.ResultProto.Student.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasLastname()) {
          bitField0_ |= 0x00000002;
          lastname_ = other.lastname_;
          onChanged();
        }
        if (other.hasFirstname()) {
          bitField0_ |= 0x00000004;
          firstname_ = other.firstname_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000008;
          email_ = other.email_;
          onChanged();
        }
        if (marksBuilder_ == null) {
          if (!other.marks_.isEmpty()) {
            if (marks_.isEmpty()) {
              marks_ = other.marks_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMarksIsMutable();
              marks_.addAll(other.marks_);
            }
            onChanged();
          }
        } else {
          if (!other.marks_.isEmpty()) {
            if (marksBuilder_.isEmpty()) {
              marksBuilder_.dispose();
              marksBuilder_ = null;
              marks_ = other.marks_;
              bitField0_ = (bitField0_ & ~0x00000010);
              marksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMarksFieldBuilder() : null;
            } else {
              marksBuilder_.addAllMessages(other.marks_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasLastname()) {
          return false;
        }
        if (!hasFirstname()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.tutorial.ResultProto.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.tutorial.ResultProto.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastname_ = "";
      /**
       * <code>required string lastname = 2;</code>
       */
      public boolean hasLastname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string lastname = 2;</code>
       */
      public java.lang.String getLastname() {
        java.lang.Object ref = lastname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string lastname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        java.lang.Object ref = lastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string lastname = 2;</code>
       */
      public Builder setLastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string lastname = 2;</code>
       */
      public Builder clearLastname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastname_ = getDefaultInstance().getLastname();
        onChanged();
        return this;
      }
      /**
       * <code>required string lastname = 2;</code>
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object firstname_ = "";
      /**
       * <code>required string firstname = 3;</code>
       */
      public boolean hasFirstname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public java.lang.String getFirstname() {
        java.lang.Object ref = firstname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFirstnameBytes() {
        java.lang.Object ref = firstname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public Builder setFirstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        firstname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public Builder clearFirstname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        firstname_ = getDefaultInstance().getFirstname();
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public Builder setFirstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        firstname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 4;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000008);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.example.tutorial.ResultProto.CourseMarks> marks_ =
        java.util.Collections.emptyList();
      private void ensureMarksIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          marks_ = new java.util.ArrayList<com.example.tutorial.ResultProto.CourseMarks>(marks_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.tutorial.ResultProto.CourseMarks, com.example.tutorial.ResultProto.CourseMarks.Builder, com.example.tutorial.ResultProto.CourseMarksOrBuilder> marksBuilder_;

      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public java.util.List<com.example.tutorial.ResultProto.CourseMarks> getMarksList() {
        if (marksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(marks_);
        } else {
          return marksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public int getMarksCount() {
        if (marksBuilder_ == null) {
          return marks_.size();
        } else {
          return marksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public com.example.tutorial.ResultProto.CourseMarks getMarks(int index) {
        if (marksBuilder_ == null) {
          return marks_.get(index);
        } else {
          return marksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public Builder setMarks(
          int index, com.example.tutorial.ResultProto.CourseMarks value) {
        if (marksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarksIsMutable();
          marks_.set(index, value);
          onChanged();
        } else {
          marksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public Builder setMarks(
          int index, com.example.tutorial.ResultProto.CourseMarks.Builder builderForValue) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          marks_.set(index, builderForValue.build());
          onChanged();
        } else {
          marksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public Builder addMarks(com.example.tutorial.ResultProto.CourseMarks value) {
        if (marksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarksIsMutable();
          marks_.add(value);
          onChanged();
        } else {
          marksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public Builder addMarks(
          int index, com.example.tutorial.ResultProto.CourseMarks value) {
        if (marksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarksIsMutable();
          marks_.add(index, value);
          onChanged();
        } else {
          marksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public Builder addMarks(
          com.example.tutorial.ResultProto.CourseMarks.Builder builderForValue) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          marks_.add(builderForValue.build());
          onChanged();
        } else {
          marksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public Builder addMarks(
          int index, com.example.tutorial.ResultProto.CourseMarks.Builder builderForValue) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          marks_.add(index, builderForValue.build());
          onChanged();
        } else {
          marksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public Builder addAllMarks(
          java.lang.Iterable<? extends com.example.tutorial.ResultProto.CourseMarks> values) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, marks_);
          onChanged();
        } else {
          marksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public Builder clearMarks() {
        if (marksBuilder_ == null) {
          marks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          marksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public Builder removeMarks(int index) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          marks_.remove(index);
          onChanged();
        } else {
          marksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public com.example.tutorial.ResultProto.CourseMarks.Builder getMarksBuilder(
          int index) {
        return getMarksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public com.example.tutorial.ResultProto.CourseMarksOrBuilder getMarksOrBuilder(
          int index) {
        if (marksBuilder_ == null) {
          return marks_.get(index);  } else {
          return marksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public java.util.List<? extends com.example.tutorial.ResultProto.CourseMarksOrBuilder> 
           getMarksOrBuilderList() {
        if (marksBuilder_ != null) {
          return marksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(marks_);
        }
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public com.example.tutorial.ResultProto.CourseMarks.Builder addMarksBuilder() {
        return getMarksFieldBuilder().addBuilder(
            com.example.tutorial.ResultProto.CourseMarks.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public com.example.tutorial.ResultProto.CourseMarks.Builder addMarksBuilder(
          int index) {
        return getMarksFieldBuilder().addBuilder(
            index, com.example.tutorial.ResultProto.CourseMarks.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.CourseMarks marks = 5;</code>
       */
      public java.util.List<com.example.tutorial.ResultProto.CourseMarks.Builder> 
           getMarksBuilderList() {
        return getMarksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.tutorial.ResultProto.CourseMarks, com.example.tutorial.ResultProto.CourseMarks.Builder, com.example.tutorial.ResultProto.CourseMarksOrBuilder> 
          getMarksFieldBuilder() {
        if (marksBuilder_ == null) {
          marksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.tutorial.ResultProto.CourseMarks, com.example.tutorial.ResultProto.CourseMarks.Builder, com.example.tutorial.ResultProto.CourseMarksOrBuilder>(
                  marks_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          marks_ = null;
        }
        return marksBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Student)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Student)
    private static final com.example.tutorial.ResultProto.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.tutorial.ResultProto.Student();
    }

    public static com.example.tutorial.ResultProto.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    public com.example.tutorial.ResultProto.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    java.util.List<com.example.tutorial.ResultProto.Student> 
        getStudentList();
    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    com.example.tutorial.ResultProto.Student getStudent(int index);
    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    int getStudentCount();
    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    java.util.List<? extends com.example.tutorial.ResultProto.StudentOrBuilder> 
        getStudentOrBuilderList();
    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    com.example.tutorial.ResultProto.StudentOrBuilder getStudentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.Result}
   */
  public  static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Result)
      ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      student_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                student_ = new java.util.ArrayList<com.example.tutorial.ResultProto.Student>();
                mutable_bitField0_ |= 0x00000001;
              }
              student_.add(
                  input.readMessage(com.example.tutorial.ResultProto.Student.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          student_ = java.util.Collections.unmodifiableList(student_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.ResultProto.internal_static_tutorial_Result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.ResultProto.internal_static_tutorial_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tutorial.ResultProto.Result.class, com.example.tutorial.ResultProto.Result.Builder.class);
    }

    public static final int STUDENT_FIELD_NUMBER = 1;
    private java.util.List<com.example.tutorial.ResultProto.Student> student_;
    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    public java.util.List<com.example.tutorial.ResultProto.Student> getStudentList() {
      return student_;
    }
    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    public java.util.List<? extends com.example.tutorial.ResultProto.StudentOrBuilder> 
        getStudentOrBuilderList() {
      return student_;
    }
    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    public int getStudentCount() {
      return student_.size();
    }
    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    public com.example.tutorial.ResultProto.Student getStudent(int index) {
      return student_.get(index);
    }
    /**
     * <code>repeated .tutorial.Student student = 1;</code>
     */
    public com.example.tutorial.ResultProto.StudentOrBuilder getStudentOrBuilder(
        int index) {
      return student_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getStudentCount(); i++) {
        if (!getStudent(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < student_.size(); i++) {
        output.writeMessage(1, student_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < student_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, student_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.tutorial.ResultProto.Result)) {
        return super.equals(obj);
      }
      com.example.tutorial.ResultProto.Result other = (com.example.tutorial.ResultProto.Result) obj;

      boolean result = true;
      result = result && getStudentList()
          .equals(other.getStudentList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getStudentCount() > 0) {
        hash = (37 * hash) + STUDENT_FIELD_NUMBER;
        hash = (53 * hash) + getStudentList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.tutorial.ResultProto.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.ResultProto.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.ResultProto.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.tutorial.ResultProto.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.tutorial.ResultProto.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.tutorial.ResultProto.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.tutorial.ResultProto.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.tutorial.ResultProto.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Result)
        com.example.tutorial.ResultProto.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.ResultProto.internal_static_tutorial_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.ResultProto.internal_static_tutorial_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.tutorial.ResultProto.Result.class, com.example.tutorial.ResultProto.Result.Builder.class);
      }

      // Construct using com.example.tutorial.ResultProto.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStudentFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (studentBuilder_ == null) {
          student_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          studentBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.ResultProto.internal_static_tutorial_Result_descriptor;
      }

      public com.example.tutorial.ResultProto.Result getDefaultInstanceForType() {
        return com.example.tutorial.ResultProto.Result.getDefaultInstance();
      }

      public com.example.tutorial.ResultProto.Result build() {
        com.example.tutorial.ResultProto.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.tutorial.ResultProto.Result buildPartial() {
        com.example.tutorial.ResultProto.Result result = new com.example.tutorial.ResultProto.Result(this);
        int from_bitField0_ = bitField0_;
        if (studentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            student_ = java.util.Collections.unmodifiableList(student_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.student_ = student_;
        } else {
          result.student_ = studentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.ResultProto.Result) {
          return mergeFrom((com.example.tutorial.ResultProto.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.tutorial.ResultProto.Result other) {
        if (other == com.example.tutorial.ResultProto.Result.getDefaultInstance()) return this;
        if (studentBuilder_ == null) {
          if (!other.student_.isEmpty()) {
            if (student_.isEmpty()) {
              student_ = other.student_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStudentIsMutable();
              student_.addAll(other.student_);
            }
            onChanged();
          }
        } else {
          if (!other.student_.isEmpty()) {
            if (studentBuilder_.isEmpty()) {
              studentBuilder_.dispose();
              studentBuilder_ = null;
              student_ = other.student_;
              bitField0_ = (bitField0_ & ~0x00000001);
              studentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStudentFieldBuilder() : null;
            } else {
              studentBuilder_.addAllMessages(other.student_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getStudentCount(); i++) {
          if (!getStudent(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.tutorial.ResultProto.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.tutorial.ResultProto.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.tutorial.ResultProto.Student> student_ =
        java.util.Collections.emptyList();
      private void ensureStudentIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          student_ = new java.util.ArrayList<com.example.tutorial.ResultProto.Student>(student_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.tutorial.ResultProto.Student, com.example.tutorial.ResultProto.Student.Builder, com.example.tutorial.ResultProto.StudentOrBuilder> studentBuilder_;

      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public java.util.List<com.example.tutorial.ResultProto.Student> getStudentList() {
        if (studentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(student_);
        } else {
          return studentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public int getStudentCount() {
        if (studentBuilder_ == null) {
          return student_.size();
        } else {
          return studentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public com.example.tutorial.ResultProto.Student getStudent(int index) {
        if (studentBuilder_ == null) {
          return student_.get(index);
        } else {
          return studentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public Builder setStudent(
          int index, com.example.tutorial.ResultProto.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentIsMutable();
          student_.set(index, value);
          onChanged();
        } else {
          studentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public Builder setStudent(
          int index, com.example.tutorial.ResultProto.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public Builder addStudent(com.example.tutorial.ResultProto.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentIsMutable();
          student_.add(value);
          onChanged();
        } else {
          studentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public Builder addStudent(
          int index, com.example.tutorial.ResultProto.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentIsMutable();
          student_.add(index, value);
          onChanged();
        } else {
          studentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public Builder addStudent(
          com.example.tutorial.ResultProto.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.add(builderForValue.build());
          onChanged();
        } else {
          studentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public Builder addStudent(
          int index, com.example.tutorial.ResultProto.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public Builder addAllStudent(
          java.lang.Iterable<? extends com.example.tutorial.ResultProto.Student> values) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, student_);
          onChanged();
        } else {
          studentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          student_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public Builder removeStudent(int index) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.remove(index);
          onChanged();
        } else {
          studentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public com.example.tutorial.ResultProto.Student.Builder getStudentBuilder(
          int index) {
        return getStudentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public com.example.tutorial.ResultProto.StudentOrBuilder getStudentOrBuilder(
          int index) {
        if (studentBuilder_ == null) {
          return student_.get(index);  } else {
          return studentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public java.util.List<? extends com.example.tutorial.ResultProto.StudentOrBuilder> 
           getStudentOrBuilderList() {
        if (studentBuilder_ != null) {
          return studentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(student_);
        }
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public com.example.tutorial.ResultProto.Student.Builder addStudentBuilder() {
        return getStudentFieldBuilder().addBuilder(
            com.example.tutorial.ResultProto.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public com.example.tutorial.ResultProto.Student.Builder addStudentBuilder(
          int index) {
        return getStudentFieldBuilder().addBuilder(
            index, com.example.tutorial.ResultProto.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Student student = 1;</code>
       */
      public java.util.List<com.example.tutorial.ResultProto.Student.Builder> 
           getStudentBuilderList() {
        return getStudentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.tutorial.ResultProto.Student, com.example.tutorial.ResultProto.Student.Builder, com.example.tutorial.ResultProto.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.tutorial.ResultProto.Student, com.example.tutorial.ResultProto.Student.Builder, com.example.tutorial.ResultProto.StudentOrBuilder>(
                  student_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          student_ = null;
        }
        return studentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Result)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Result)
    private static final com.example.tutorial.ResultProto.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.tutorial.ResultProto.Result();
    }

    public static com.example.tutorial.ResultProto.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    public com.example.tutorial.ResultProto.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_CourseMarks_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_CourseMarks_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protocol_defn.proto\022\010tutorial\"*\n\013Cours" +
      "eMarks\022\014\n\004name\030\001 \001(\t\022\r\n\005score\030\002 \001(\005\"o\n\007S" +
      "tudent\022\n\n\002id\030\001 \002(\t\022\020\n\010lastname\030\002 \002(\t\022\021\n\t" +
      "firstname\030\003 \002(\t\022\r\n\005email\030\004 \001(\t\022$\n\005marks\030" +
      "\005 \003(\0132\025.tutorial.CourseMarks\",\n\006Result\022\"" +
      "\n\007student\030\001 \003(\0132\021.tutorial.StudentB#\n\024co" +
      "m.example.tutorialB\013ResultProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_CourseMarks_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_CourseMarks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_CourseMarks_descriptor,
        new java.lang.String[] { "Name", "Score", });
    internal_static_tutorial_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Student_descriptor,
        new java.lang.String[] { "Id", "Lastname", "Firstname", "Email", "Marks", });
    internal_static_tutorial_Result_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Result_descriptor,
        new java.lang.String[] { "Student", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
